# Generated by Django 4.1.6 on 2023-02-17 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Meuapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='tipo_user',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
