# Generated by Django 4.1.6 on 2023-02-17 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Meuapp', '0002_usuario_tipo_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_Produto', models.CharField(max_length=20, null=True)),
                ('descricao', models.CharField(max_length=60, null=True)),
            ],
        ),
    ]
