# Generated by Django 4.1.6 on 2023-03-01 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Meuapp', '0005_produto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Produto',
        ),
    ]
